### ISSUE TITLE
getRaw not serializing named nodes

### ISSUE THREAD

**Issue by devel-pa** [gkz/grasp#55]
Hi, good stuff for fast code refactoring and functionality extraction.
Not working for me, yet, but with some hope :D .

I am using grasp as a library.

Use case: I want to extract the content of a function. Lets say:

```
function (Backbone) {
    return Backbone.View.extend({});
}
```

the function used is this:
```
var processedCode =  grasp.replace('equery',
  expression,
  function(getRaw, node, query, named){
    return getRaw(named.content);
}, code);
```

where the expresion can be:

```
var expression = 'function (Backbone) {__}'
```
no nodes found

```
'function (Backbone) {$fcContent}'
```
no nodes found.

```
'function (Backbone) {_$fcContent}'
```
hoorayyy, works.
but getRaw retuns empty string from named and named.fcContent.
Also 

```
getRaw(node.body)
```
returns the curly brackets, too.

Thanks.

PS: Some update to the site documentation, pls.

PS2: what is the use of `search`?

PS3: not mentioning that in fact the sample code is covered with double parenthesis which magically disappears. Which I like :)

**Comment by gkz** [comment]
Hi, thanks for using Grasp!
The body of a function is a "BlockStatement"
A BlockStatement contains a property "body" that contains an array of statements.

```
var expression = 'function(Backbone) { $content }';
```

Works if there is only one statement in the body of the function, and it will match that statement.

Using `_$content` will match the array of statements. If you match with `_$content`, you must join the array in the way that you want. Eg. `named.content.map(getRaw).join("\n")`, or just select one of the items in the array and use `getRaw`.

`getRaw(node.body)` returns curly braces because `node.body` is a "BlockStatement", which is an array of statements surrounded by curly braces. 

I would check out http://www.graspjs.com/docs/syntax-js/ in the future for more information.

**Comment by devel-pa** [comment]
Thank you very much for clarification. Works like a charm.
